version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/var/www
    command: "composer install"
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app
    command: >
      sh -c "
      yarn install
      yarn dev
      "
    ports:
      - 80:3000
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bulletin-board
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql-volume:
